### PR TITLE
Changes to plot styles and python scripts

### PR DESCRIPTION
**Pull request by tom-so**
For the changes to PlotBinnedSamples.py see [here](https://github.com/UHH2/VHResonances/commit/8cdc59a82054fb73f1e575c483ad26a6b2564235). The second commit changes all line endings from CRLF to LF and all therefore lines.
The third commit, [281d0e9](https://github.com/UHH2/VHResonances/commit/281d0e903b45eec15d39ce5d03f847bf2eabe748) changes the label styles for some histograms. These changes were parts of the comments received after the rehearsal talk. Also, some axis limits are changed, mainly in line 66 of the file "src/HiggsToWWHists.cxx": `book_TH1F(name+"_pt",      "p_{T}^"   +name+" [GeV]",  500,  0,  5000);`

### CODE REVIEW

**Review by anmalara — COMMENTED** [review]
Why the change in L492vs L505 in src/HiggsToWWHist.cxx?

**Comment by tom-so** [comment]
What has changed is the axis label from `[GeV]` to `[GeV/c^{2}]`.
The position in the code has changed because I did some other changes that I didn't commit (I removed the histograms in the `for` loop and two histograms about the H4q tagger.)

Do you prefer the `c^2` to be removed?

**Comment by anmalara** [comment]
I'm talking about the Zprime plots that now are inside the for loop. They should be outside, right?

**Comment by tom-so** [comment]
The for loop ends in the new line 501 and the changed code starts in new line 505.

**Comment by anmalara** [comment]
I see. From the git diff looked strange.

**Pull request merged**
