### PR TITLE
Implement Zprime reconstruction for the invisible channel

### PR DESCRIPTION
**Pull request by tom-so**
Implementation of the Z' reconstruction of the invisible channel using a branch.

I created a new function which is called for both the invisible and lepton channel.

The first five commits are meant to be dealt with PR #37.

### CODE REVIEW

**Review by anmalara — COMMENTED** [review]
How about moving "neutrinos" -> "invisible"?

HiggsToWWModules.cxx:

- L206:  "and" -> &&. maybe for consistency? It's right in any case.
- L115: Can you with LorentzVector instead of the long constructors? 
- L116: No need to pass diLep. It can be calculated afterwards. Same for ZplusJet
- L117: No need to pass both MuonID1(2) and i(j).
- L249: why? 
- I'm not convinced by the order of the parameters in the constructor. Many can have a default value that simplify the constructor I think.

**Comment by tom-so** [comment]
L206: Done
L114: What would a better constructor be?
L116: I am passing diLep so that I can set diLep to the MET for the invisible channel. The reconstruction itself is work in progress with the transversal masses, so this needs to be improved in the future.
L117: I don't understand the meaning of the i and j's (they are not explained in comments) so I just hand them to the function. (Actually, the whole function is just cut & pasted from the code from the leptonchannel, I did not change anything at all.)
L2

**Comment by anmalara** [comment]
L117: They are the indices of the leptons. We use them to store the information of which lepton we have been using. It's needed for the lepton trigger and ID SFs.
L116: You can construct the diLep and ZplusJet inside the function, starting from lep1, lep2 and the jet.

The rest is fine. You just need to prove that everything works and nothing is broken. I'll merge after we have some plots.

**Comment by tom-so** [comment]
Closing the PR because the changes are implemented in #41, #42, #43, #44 and #45.

**Pull request closed without merging**
