### PR TITLE
Changes to HiggsToWWModules 

### PR DESCRIPTION
**Pull request by tom-so**
There are some lines that need to be changed in SelectionModule.cxx which I did not commit yet.
It needs to say `MS["leptons"] = MB["muonchannel"]? "muons": (MB["electronchannel"]? "electrons": (MB["invisiblechannel"]? "invisible": ""));` and some lines need to be commented (containing "BTag", "SFs" and cuts that are not run yet for this channel).

### CODE REVIEW

**Review by anmalara — COMMENTED** [review]
L258: can you use the DeltaPhi function?
L254: Move the candidate just before the setDiscriminators

**Comment by tom-so** [comment]
L258: I did not get it to work... I think it is because is says `particle1.phi()` with a "." but for MET it needs the arrow "->": `event.met->phi()`
L254: done

**Comment by anmalara** [comment]
The  constructor is here:
https://github.com/UHH2/UHH2/blob/63a768458ddceeadaebd04469da0ab058e2afb5a/core/include/LorentzVector.h#L37

Did you try with DeltaPhi(jet,*event.met)?

**Comment by tom-so** [comment]
It works with *event.met.
I added the one line in SelectionModule.

**Pull request merged**
